# Generated by Django 3.2.4 on 2022-03-21 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user1LastMessageRead',
            field=models.ForeignKey(blank=True, db_column='user1LastMessageReadId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messenger_backend.message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2LastMessageRead',
            field=models.ForeignKey(blank=True, db_column='user2LastMessageReadId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messenger_backend.message'),
        ),
    ]
