# Generated by Django 3.2.4 on 2022-03-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_auto_20220322_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='conversation',
        ),
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(to='messenger_backend.Participant'),
        ),
    ]
